LED_FEED = 'bk-iot-led'
SOIL_FEED = 'bk-iot-soil'
LIGHT_FEED = 'bk-iot-light'
LCD_FEED = 'bk-iot-lcd'
RELAY_FEED = 'bk-iot-relay'
DHT11_FEED = 'bk-iot-temp-humid'
all_feeds = [LED_FEED,SOIL_FEED,LCD_FEED,DHT11_FEED,LIGHT_FEED,RELAY_FEED]
feed_pub =[LED_FEED, LCD_FEED, RELAY_FEED]
feeds_of_client = [[LED_FEED,SOIL_FEED,LCD_FEED,DHT11_FEED],[LIGHT_FEED,RELAY_FEED]]
ADAFRUIT_IO_USERNAME0, ADAFRUIT_IO_KEYBBC0 = 'trminhhien17', 'aio_Phfr33tNoyth68Tg6gWsVJXNkVbA'
ADAFRUIT_IO_USERNAME1, ADAFRUIT_IO_KEYBBC1 = 'trminhhien17', 'aio_Phfr33tNoyth68Tg6gWsVJXNkVbA'
