import os
ADAFRUIT_IO_USERNAME0, ADAFRUIT_IO_KEYBBC0 = 'trminhhien17', 'aio_Phfr33tNoyth68Tg6gWsVJXNkVbA'
ADAFRUIT_IO_USERNAME1, ADAFRUIT_IO_KEYBBC1 = 'trminhhien17', 'aio_Phfr33tNoyth68Tg6gWsVJXNkVbA'

#ADAFRUIT_IO_USERNAME0, ADAFRUIT_IO_KEYBBC0 = 'CSE_BBC', os.environ[CSE_BBC]
#ADAFRUIT_IO_USERNAME1, ADAFRUIT_IO_KEYBBC1 = 'CSE_BBC1', os.environ[CSE_BBC1]
